services:
  bd_clientes:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bd_clientes
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=UPT.2024
    volumes:
      - ./db/clientes.sql:/tmp/clientes.sql:ro

  api:
    build: ./ClienteAPI                 # apunta a la carpeta que ya tiene Dockerfile
    container_name: api_clientes
    ports:
      - "5149:8080"
    environment:
      - ConnectionStrings__ClienteDB=Server=bd_clientes;Database=BD_CLIENTES;User Id=sa;Password=UPT.2024;TrustServerCertificate=true
    depends_on:
      - bd_clientes

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./metrics/grafana_ds:/etc/grafana/provisioning/datasources
      - ./metrics/grafana_db:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
