global:
  scrape_interval: 3s
  evaluation_interval: 1m

scrape_configs:
  - job_name: apiCliente
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8080

  - job_name: clienteapi-health
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8080
    relabel_configs:
      - source_labels: [__name__]
        regex: db_health_status
        action: keep
