name: Build and Publish API Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build API
        run: dotnet publish ClienteAPI/ClienteAPI.csproj -c Release -o out

      - name: Build Docker image
        run: |
          # Contexto ClienteAPI/, Dockerfile en ClienteAPI/Dockerfile
          docker build --no-cache ClienteAPI \
            -f ClienteAPI/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USER }}/clienteapi:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/clienteapi:${{ github.sha }}

      - name: Set image output
        id: image_info
        run: |
          echo "::set-output name=image::${{ secrets.DOCKERHUB_USER }}/clienteapi:${{ github.sha }}"
